ancestor: null
releases:
  1.0.0:
    changes:
      release_summary: Initial release of this collection.
    fragments:
    - 1.0.0.yml
    plugins:
      lookup:
      - description: Composes a list with nested elements of other lists or dicts
          which can depend on previous indices
        name: felixfontein.tools.dependent
        namespace: null
    release_date: '2020-05-23'
  1.0.1:
    changes:
      release_summary: 'Maintenance release for internal changes. Visible external
        change is that the changelog moved one directory up.

        '
    fragments:
    - 1.0.1.yml
    release_date: '2020-11-07'
  1.1.0:
    changes:
      minor_changes:
      - 'Added ``felixfontein.tools.path_join`` filter. For ansible-base 2.10 or newer,
        it redirects to ``ansible.builtin.path_join``. For Ansible 2.9 and before,
        it provides an own implementation for the most important case: joining a list
        of path fragments.'
      - Added filter plugins ``dns_zone``, ``dns_zone_prefix``, ``get_domain_suffix``
        and ``remove_domain_suffix``.
      release_summary: This release enables CI and adds several useful filters.
    fragments:
    - 1.1.0.yml
    - domain-suffix.yml
    - path_join-shim.yml
    release_date: '2020-11-07'
  1.2.0:
    changes:
      minor_changes:
      - Update Public Suffix List to latest version (https://github.com/felixfontein/ansible-tools/pull/4).
    fragments:
    - 4-update-psl.yml
    release_date: '2021-01-31'
