ancestor: null
releases:
  1.0.0:
    changes:
      release_summary: Initial release of this collection.
    fragments:
    - 1.0.0.yml
    plugins:
      lookup:
      - description: Composes a list with nested elements of other lists or dicts
          which can depend on previous indices
        name: dependent
        namespace: null
    release_date: '2020-05-23'
  1.0.1:
    changes:
      release_summary: 'Maintenance release for internal changes. Visible external
        change is that the changelog moved one directory up.

        '
    fragments:
    - 1.0.1.yml
    release_date: '2020-11-07'
  1.1.0:
    changes:
      minor_changes:
      - 'Added ``felixfontein.tools.path_join`` filter. For ansible-base 2.10 or newer,
        it redirects to ``ansible.builtin.path_join``. For Ansible 2.9 and before,
        it provides an own implementation for the most important case: joining a list
        of path fragments.'
      release_summary: This release enables CI and adds several useful filters.
    fragments:
    - 1.1.0.yml
    - path_join-shim.yml
    plugins:
      filter:
      - description: "Return the DNS zone of a domain name (``www.ansible.com`` \u2192
          ``ansible.com``)"
        name: dns_zone
        namespace: null
      - description: "Return the prefix before the DNS zone for a domain name (``www.ansible.com``
          \u2192 ``www``)"
        name: dns_zone_prefix
        namespace: null
      - description: "Return the public suffix for a domain name (``www.ansible.com``
          \u2192 ``.com``)"
        name: get_domain_suffix
        namespace: null
      - description: Ansible 2.9 compatibility shim for the ``ansible.builtin.path_join``
          filter included in ansible-base 2.10
        name: path_join
        namespace: null
      - description: "Return the part before the public suffix for a domain name (``www.ansible.com``
          \u2192 ``www.ansible``)"
        name: remove_domain_suffix
        namespace: null
    release_date: '2020-11-07'
  1.2.0:
    changes:
      minor_changes:
      - Update Public Suffix List to latest version (https://github.com/felixfontein/ansible-tools/pull/4).
    fragments:
    - 4-update-psl.yml
    release_date: '2021-01-31'
  1.3.0:
    changes:
      minor_changes:
      - The public suffix list (PSL) matching algorithm as specified on https://publicsuffix.org/list/
        is now used.
      - The public suffix list (PSL) was updated.
      release_summary: Completely rewrote the Public Suffix List handling code.
    fragments:
    - 1.3.0.yml
    - psl-matching.yml
    - psl-updated.yml
    release_date: '2021-02-22'
  1.4.0:
    changes:
      release_summary: This release adds several DNS-related new plugins, and two
        filters which make creating dictionaries easier.
    fragments:
    - 1.4.0.yml
    - dict.yml
    - registrable-domain.yml
    modules:
    - description: Wait for TXT entries to be available on all authoritative nameservers
      name: wait_for_txt
      namespace: ''
    plugins:
      filter:
      - description: 'The ``dict`` function as a filter: converts a list of tuples
          to a dictionary'
        name: dict
        namespace: null
      - description: Given a list of values and a list of keys, converts them to a
          dictionary
        name: list_to_dict
        namespace: null
      - description: Given domain name, returns the registrable domain
        name: registrable_domain
        namespace: null
      test:
      - description: Given domain name, tests whether it is a registrable domain
        name: is_registrable_domain
        namespace: null
    release_date: '2021-03-04'
